name = "CapAndHomalg"
uuid = "c4774649-1891-41ea-a883-87141804c57c"
authors = ["Mohamed Barakat <mohamed.barakat@uni-siegen.de>"]
version = "1.3.4"

[deps]
GAP = "c863536a-3901-11e9-33e7-d5cd0df7b904"
Graphviz_jll = "3c863552-8265-54e4-a6dc-903eb78fde85"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Singular_jll = "43d676ae-4934-50ba-8046-7a96366d613b"
lib4ti2_jll = "1493ae25-0f90-5c0e-a06c-8c5077d6d66f"

[compat]
GAP = "0.7, 0.8"
julia = "1.6"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter"]
